CREATE TABLE IF NOT EXISTS contacts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    telefono VARCHAR(30) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    empresa VARCHAR(150) NULL,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    uso_codigo TINYINT(1) NOT NULL DEFAULT 0,
    created_at_utc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
